[project]
name = "sample_learn"
version = "0.1.0"
description = "sample_learn using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.102.0,<1.0.0"
]

[project.scripts]
sample_learn = "sample_learn.main:run"
run_crew = "sample_learn.main:run"
train = "sample_learn.main:train"
replay = "sample_learn.main:replay"
test = "sample_learn.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
