[project]
name = "day_06"
version = "0.1.0"
description = "day_06 using crewAI"
authors = [
    { name = "Tyler Reed", email = "tylerreedytlearning@gmail.com" },
]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "crewai[tools]>=0.67.1,<1.0.0",
]

[project.scripts]
day_06 = "day_06.main:run"
run_crew = "day_06.main:run"
train = "day_06.main:train"
replay = "day_06.main:replay"
test = "day_06.main:test"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"
